"""Generate `SageLint.sublime-syntax` from the typed model.

The highlighter's keyword lists are not hand-maintained: the block keywords (top-level
definition classes like `Object`, `Weapon`, `Upgrade`) and the type names (every modelled
class, so a module after `=` such as `AutoHealBehavior` highlights too) are read straight
from `sage_ini`'s class registry — the same source the parser and the editor's symbol index
use. Re-run this whenever the model grows:

    python sage_lint/plugins/sublime/generate_syntax.py

It overwrites `SageLint.sublime-syntax` in this folder. The syntax keeps the conventional
`source.ini` scope so the package's `source.ini`-scoped key bindings keep working on files
opened with it; standard sub-scopes (keyword, storage.type, comment, string, …) mean any
colour scheme highlights it without extra configuration.
"""

from pathlib import Path

import sage_ini.model.definitions  # noqa: F401  (populate the class registry)
from sage_ini.model.objects import REGISTRY

_HERE = Path(__file__).resolve().parent
_OUTPUT = _HERE / "SageLint.sublime-syntax"

# Directives that open the engine's preprocessor lines.
_DIRECTIVES = ("define", "include", "undef", "ifdef", "ifndef", "else", "endif", "set")


def _alternation(names: list[str]) -> str:
    """A regex alternation of `names`, longest first so a `\\b`-bounded match never settles for
    a shorter prefix (`Object` vs `ObjectCreationList`)."""
    ordered = sorted(set(names), key=lambda name: (-len(name), name))
    return "|".join(ordered)


def _keyword_sets() -> tuple[str, str]:
    """`(block_keywords, type_names)` alternations from the registry: block keywords are the
    table-backed top-level definition classes (their class name is the block header); type
    names are every modelled class, highlighting module classes and reference types wherever
    they appear."""
    # `_`-prefixed registry entries are abstract bases (`_EvaEventBase`); they never appear in
    # source, so leave them out of the keyword lists.
    public = {name: cls for name, cls in REGISTRY.items() if not name.startswith("_")}
    block = [name for name, cls in public.items() if getattr(cls, "key", None) is not None]
    return _alternation(block), _alternation(list(public))


def render() -> str:
    block_keywords, type_names = _keyword_sets()
    directives = "|".join(_DIRECTIVES)
    return f"""%YAML 1.2
---
# GENERATED by generate_syntax.py from sage_ini's class registry — do not edit by hand.
# Re-run `python sage_lint/plugins/sublime/generate_syntax.py` to refresh the keyword lists.
name: Sage Lint
file_extensions: [ini, inc, bhav]
scope: source.ini

variables:
  block_keywords: '{block_keywords}'
  type_names: '{type_names}'

contexts:
  main:
    - include: comments
    - include: strings
    - include: directives
    - include: block_headers
    - include: field_keys
    - include: values
    - include: booleans
    - include: numbers

  comments:
    - match: '(//|;).*$'
      scope: comment.line.sageini

  strings:
    # SAGE has no string escapes: a backslash is a literal path separator (`Data\\INI\\...`),
    # so the only thing that ends a string is the closing quote.
    - match: '"'
      scope: punctuation.definition.string.begin.sageini
      push:
        - meta_scope: string.quoted.double.sageini
        - match: '"'
          scope: punctuation.definition.string.end.sageini
          pop: true

  directives:
    - match: '(?i)^\\s*#({directives})\\b'
      scope: keyword.control.preprocessor.sageini

  block_headers:
    # `End` closes a block (case-insensitive, as the engine reads it).
    - match: '(?i)\\bEnd\\b'
      scope: keyword.control.end.sageini
    # A top-level definition header (`Object Foo`, `Weapon Bar`) at the start of a line.
    - match: '^\\s*({{{{block_keywords}}}})\\b'
      scope: keyword.control.block.sageini

  field_keys:
    # `Key = value`: the key (also a module slot like `Behavior =`) is a member.
    - match: '^\\s*([A-Za-z_][\\w%]*)\\s*(?==)'
      captures:
        1: variable.other.member.sageini

  booleans:
    - match: '(?i)\\b(Yes|No|True|False)\\b'
      scope: constant.language.boolean.sageini

  numbers:
    - match: '\\b-?[0-9]+(\\.[0-9]+)?[%f]?\\b'
      scope: constant.numeric.sageini

  values:
    # A modelled class name only in value position — the module after `Behavior =`, a typed
    # reference. Restricting it to after `=` keeps class names that are also ordinary words
    # (`Fire`, `Road`, `Color`) plain everywhere else, so highlighting stays quiet.
    - match: '(=)\\s*({{{{type_names}}}})\\b'
      captures:
        1: keyword.operator.assignment.sageini
        2: storage.type.class.sageini
"""


def main() -> None:
    _OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
